'use client';

import { createContext, useContext } from 'react';

export type OrbitLanguage = 'en' | 'uk' | 'ru';

export const orbitLanguages: { id: OrbitLanguage; code: string; nativeName: string; englishName: string }[] = [
  { id: 'uk', code: 'UA', nativeName: 'Українська', englishName: 'Ukrainian' },
  { id: 'ru', code: 'RU', nativeName: 'Русский', englishName: 'Russian' },
  { id: 'en', code: 'EN', nativeName: 'English', englishName: 'English' },
];

const translations: Record<Exclude<OrbitLanguage, 'en'>, Record<string, string>> = {
  uk: {
    Home: 'Головна', Market: 'Маркет', Cases: 'Кейси', Profile: 'Профіль', Light: 'Світла', Dark: 'Темна',
    Lucky: 'Удача', 'Main navigation': 'Головна навігація', 'Switch to light theme': 'Увімкнути світлу тему', 'Switch to dark theme': 'Увімкнути темну тему', 'GRAM balance': 'баланс GRAM', 'Available cases': 'Доступні кейси', 'Select background: {name}': 'Обрати фон: {name}',
    'Your balance': 'Ваш баланс', 'Connect wallet to start trading': 'Підключіть гаманець, щоб почати торгівлю', 'ORBIT WALLET': 'ГАМАНЕЦЬ ORBIT',
    'Telegram Gifts': 'Подарунки Telegram', 'Limited Gifts': 'Лімітовані подарунки', 'Rare Gifts': 'Рідкісні подарунки', 'Premium Gifts': 'Преміальні подарунки',
    Featured: 'Рекомендоване', 'View all': 'Усі', Price: 'Ціна', 'Buy now': 'Купити', 'Trending gifts': 'Популярні подарунки', 'See all': 'Усі', Buy: 'Купити',
    Marketplace: 'Маркетплейс', Filter: 'Фільтр', Sort: 'Сортування', Collection: 'Колекція', 'Available in ORBIT': 'Доступно в ORBIT',
    'Loading ORBIT stock…': 'Завантаження запасів ORBIT…', 'Marketplace is temporarily unavailable': 'Маркетплейс тимчасово недоступний', 'Could not load ORBIT stock. Please try again.': 'Не вдалося завантажити запаси ORBIT. Спробуйте ще раз.', Retry: 'Спробувати знову',
    'Nothing found': 'Нічого не знайдено', 'ORBIT has no gifts in stock yet': 'В ORBIT поки немає подарунків', 'Try another search': 'Спробуйте інший запит', 'New gifts will appear here when they are added to ORBIT stock.': 'Нові подарунки з’являться тут, щойно їх додадуть до запасів ORBIT.',
    'Search gifts...': 'Пошук подарунків...', 'Clear all filters': 'Очистити всі фільтри', 'Filter NFTs': 'Фільтр NFT', 'Filter by price, background and symbol': 'Фільтр за ціною, фоном і символом', 'Close filters': 'Закрити фільтри', 'Price range': 'Діапазон цін', From: 'Від', To: 'До', 'No limit': 'Без обмежень', Background: 'Фон', 'Choose backdrop color': 'Оберіть колір фону', 'Search background...': 'Пошук фону...', Symbol: 'Символ', 'Choose gift symbol': 'Оберіть символ подарунка', 'Search symbol...': 'Пошук символу...', 'No symbol data in the current ORBIT inventory yet. Symbols will appear here when NFT trait data is added.': 'У запасах ORBIT поки немає даних про символи. Вони з’являться, коли буде додано характеристики NFT.', 'Show {count} NFTs': 'Показати NFT: {count}', 'Sort NFTs': 'Сортування NFT', 'Rarity sorting needs Telegram attributes. Items without them are ordered by name.': 'Для сортування за рідкістю потрібні атрибути Telegram. Інші подарунки впорядковуються за назвою.', 'Close sorting': 'Закрити сортування', 'Choose collection': 'Оберіть колекцію', '{count} Telegram gift collections': 'Колекції подарунків Telegram: {count}', 'Close collections': 'Закрити колекції', 'Search collection...': 'Пошук колекції...', 'All collections': 'Усі колекції', 'No matching collections.': 'Відповідних колекцій немає.', 'Gift details': 'Інформація про подарунок', Close: 'Закрити', 'ORBIT stock': 'Запаси ORBIT',
    'Pick a case and see what’s inside.': 'Оберіть кейс і подивіться, що всередині.', DEMO: 'ДЕМО', 'Crypto gifts · 5 possible NFTs': 'Криптоподарунки · 5 можливих NFT', 'View case': 'Переглянути кейс', 'More cases soon': 'Скоро більше кейсів', 'New collectible drops are on the way.': 'Незабаром з’являться нові колекції.',
    '5 collectible Telegram gifts': '5 колекційних подарунків Telegram', 'Demo only': 'Лише демо', 'No real GRAM is charged and no NFT is transferred in this preview.': 'GRAM не списуються, а NFT не передаються — це лише попередній перегляд.', 'Buy case ·': 'Купити кейс ·', 'POSSIBLE NFTS': 'МОЖЛИВІ NFT', 'What you can win': 'Можливі виграші', 'Prices in GRAM': 'Ціни в GRAM', 'DEMO RESULT': 'РЕЗУЛЬТАТ ДЕМО', 'You got {name}!': 'Ви отримали {name}!', 'Preview only. No payment was made and this NFT was not added to your profile.': 'Попередній перегляд. Оплату не списано, NFT не додано до профілю.', Continue: 'Продовжити', Open: 'Відкрити', 'Opening…': 'Відкриваємо…', 'Demo purchase complete — no GRAM was charged.': 'Демо-покупку завершено — GRAM не списувалися.',
    'LUCKY DRAW': 'РОЗІГРАШ', 'Try your luck': 'Випробуйте удачу', 'One spin. A chance to find something rare.': 'Один спін — шанс знайти рідкісний подарунок.', 'Spin cost': 'Вартість спіну', 'Demo mode: no payment or inventory changes.': 'Демо-режим: без оплати та змін в інвентарі.', 'Possible rewards': 'Можливі виграші', '6 rewards': '6 призів', Spin: 'Крутити', 'Demo result': 'Результат демо', 'You got': 'Ваш виграш', 'Demo only. Nothing was charged or added to your inventory.': 'Лише демо. GRAM не списувалися, подарунок не додано до інвентарю.', 'GRAM value': 'у GRAM',
    'Refresh profile': 'Оновити профіль', 'Telegram user': 'Користувач Telegram', 'Telegram account': 'Акаунт Telegram', 'GRAM wallet': 'Гаманець GRAM', 'No wallet connected': 'Гаманець не підключено', Connected: 'Підключено', 'Not connected': 'Не підключено', Owned: 'У власності', Listed: 'На продажу', Offers: 'Пропозиції', 'Try again': 'Спробувати знову', 'My gifts': 'Мої подарунки', 'items': 'предметів', 'No gifts yet': 'Подарунків поки немає', 'Gifts you own will appear here.': 'Подарунки у вашій власності з’являться тут.', Sell: 'Продати', 'Listed for sale': 'Виставлено на продаж', 'No active listings': 'Немає активних оголошень', 'Gifts you list for sale will appear here.': 'Подарунки, які ви виставите на продаж, з’являться тут.', 'Reserved for an accepted offer': 'Зарезервовано за прийнятою пропозицією', Edit: 'Змінити', Unlist: 'Зняти з продажу', 'My offers': 'Мої пропозиції', 'No active offers': 'Немає активних пропозицій', 'Offers you make on gifts will appear here.': 'Ваші пропозиції щодо подарунків з’являться тут.', 'Cancel offer': 'Скасувати пропозицію', 'Incoming offers': 'Вхідні пропозиції', 'No active incoming offers': 'Немає вхідних пропозицій', 'Offers for your gifts will appear here.': 'Пропозиції щодо ваших подарунків з’являться тут.', Accept: 'Прийняти', 'History': 'Історія', 'activities': 'дій', 'No activity yet': 'Поки немає активності', 'Completed actions and past offers will appear here.': 'Завершені дії та минулі пропозиції з’являться тут.', 'Edit listing price': 'Змінити ціну оголошення', 'List gift for sale': 'Виставити подарунок на продаж', 'Price in GRAM': 'Ціна в GRAM', Cancel: 'Скасувати', 'Saving…': 'Зберігаємо…', 'Save price': 'Зберегти ціну', 'Please wait…': 'Зачекайте…', Decline: 'Відхилити', 'Release reservation': 'Зняти резерв', 'This offer only reserves the gift in ORBIT. Payment and NFT transfer are not automated yet. Release it if the deal will not continue.': 'Ця пропозиція лише резервує подарунок в ORBIT. Оплата та передача NFT поки не автоматизовані. Зніміть резерв, якщо угода не відбудеться.', 'Gift purchased': 'Подарунок придбано', 'Offer accepted · awaiting payment': 'Пропозицію прийнято · очікується оплата', 'Offer cancelled': 'Пропозицію скасовано', 'Offer declined': 'Пропозицію відхилено', Gift: 'Подарунок', 'Your offer': 'Ваша пропозиція', 'Incoming offer': 'Вхідна пропозиція', 'From @{username}': 'Від @{username}',
    'Choose your language': 'Оберіть мову', 'Your language is saved on this device.': 'Мову буде збережено на цьому пристрої.', 'Language': 'Мова', 'Select language': 'Обрати мову', 'Language updated': 'Мову змінено', Start: 'Почати', 'Your next favorite gift is waiting.': 'Ваш наступний улюблений подарунок вже чекає.', 'Browse unique collectibles, discover hidden gems, and trade with ease. Everything you want, all in one place.': 'Переглядайте унікальні колекційні подарунки, знаходьте рідкісні скарби та легко торгуйте. Усе потрібне — в одному місці.', 'DIGITAL COLLECTIBLES': 'ЦИФРОВІ КОЛЕКЦІЙНІ ПОДАРУНКИ', 'WELCOME TO ORBIT': 'ЛАСКАВО ПРОСИМО ДО ORBIT',
    'Price: low to high': 'Ціна: за зростанням', 'Price: high to low': 'Ціна: за спаданням', 'Model rarity: rarest first': 'Рідкість моделі: спочатку найрідкісніші', 'Background rarity: rarest first': 'Рідкість фону: спочатку найрідкісніші', 'Symbol rarity: rarest first': 'Рідкість символу: спочатку найрідкісніші',
    'Back to cases': 'Назад до кейсів', CASE: 'КЕЙС', 'Loading profile…': 'Завантаження профілю…', offers: 'пропозицій', Pending: 'Очікує', Accepted: 'Прийнято', Cancelled: 'Скасовано', Rejected: 'Відхилено', Unlisted: 'Знято з продажу', Created: 'Створено', Paid: 'Оплачено', Completed: 'Завершено', 'Gift listed for sale': 'Подарунок виставлено на продаж', 'Listing removed': 'Оголошення знято', 'Example: 2.5': 'Наприклад: 2.5',
    'Open your profile inside the ORBIT Telegram bot to load your account.': 'Відкрийте профіль у Telegram-боті ORBIT, щоб завантажити акаунт.', 'Could not load profile': 'Не вдалося завантажити профіль', 'Could not perform action': 'Не вдалося виконати дію',
  },
  ru: {
    Home: 'Главная', Market: 'Маркет', Cases: 'Кейсы', Profile: 'Профиль', Light: 'Светлая', Dark: 'Тёмная',
    Lucky: 'Удача', 'Main navigation': 'Главная навигация', 'Switch to light theme': 'Включить светлую тему', 'Switch to dark theme': 'Включить тёмную тему', 'GRAM balance': 'баланс GRAM', 'Available cases': 'Доступные кейсы', 'Select background: {name}': 'Выбрать фон: {name}',
    'Your balance': 'Ваш баланс', 'Connect wallet to start trading': 'Подключите кошелёк, чтобы начать торговлю', 'ORBIT WALLET': 'КОШЕЛЁК ORBIT',
    'Telegram Gifts': 'Подарки Telegram', 'Limited Gifts': 'Лимитированные подарки', 'Rare Gifts': 'Редкие подарки', 'Premium Gifts': 'Премиальные подарки',
    Featured: 'Рекомендуем', 'View all': 'Все', Price: 'Цена', 'Buy now': 'Купить', 'Trending gifts': 'Популярные подарки', 'See all': 'Все', Buy: 'Купить',
    Marketplace: 'Маркетплейс', Filter: 'Фильтр', Sort: 'Сортировка', Collection: 'Коллекция', 'Available in ORBIT': 'Доступно в ORBIT',
    'Loading ORBIT stock…': 'Загрузка запасов ORBIT…', 'Marketplace is temporarily unavailable': 'Маркетплейс временно недоступен', 'Could not load ORBIT stock. Please try again.': 'Не удалось загрузить запасы ORBIT. Попробуйте ещё раз.', Retry: 'Повторить',
    'Nothing found': 'Ничего не найдено', 'ORBIT has no gifts in stock yet': 'В ORBIT пока нет подарков', 'Try another search': 'Попробуйте другой запрос', 'New gifts will appear here when they are added to ORBIT stock.': 'Новые подарки появятся здесь, когда их добавят в запасы ORBIT.',
    'Search gifts...': 'Поиск подарков...', 'Clear all filters': 'Очистить все фильтры', 'Filter NFTs': 'Фильтр NFT', 'Filter by price, background and symbol': 'Фильтр по цене, фону и символу', 'Close filters': 'Закрыть фильтры', 'Price range': 'Диапазон цен', From: 'От', To: 'До', 'No limit': 'Без ограничений', Background: 'Фон', 'Choose backdrop color': 'Выберите цвет фона', 'Search background...': 'Поиск фона...', Symbol: 'Символ', 'Choose gift symbol': 'Выберите символ подарка', 'Search symbol...': 'Поиск символа...', 'No symbol data in the current ORBIT inventory yet. Symbols will appear here when NFT trait data is added.': 'В запасах ORBIT пока нет данных о символах. Они появятся, когда будут добавлены характеристики NFT.', 'Show {count} NFTs': 'Показать NFT: {count}', 'Sort NFTs': 'Сортировка NFT', 'Rarity sorting needs Telegram attributes. Items without them are ordered by name.': 'Для сортировки по редкости нужны атрибуты Telegram. Остальные подарки сортируются по названию.', 'Close sorting': 'Закрыть сортировку', 'Choose collection': 'Выберите коллекцию', '{count} Telegram gift collections': 'Коллекций подарков Telegram: {count}', 'Close collections': 'Закрыть коллекции', 'Search collection...': 'Поиск коллекции...', 'All collections': 'Все коллекции', 'No matching collections.': 'Подходящих коллекций нет.', 'Gift details': 'Информация о подарке', Close: 'Закрыть', 'ORBIT stock': 'Запасы ORBIT',
    'Pick a case and see what’s inside.': 'Выберите кейс и посмотрите, что внутри.', DEMO: 'ДЕМО', 'Crypto gifts · 5 possible NFTs': 'Криптоподарки · 5 возможных NFT', 'View case': 'Открыть кейс', 'More cases soon': 'Скоро появятся кейсы', 'New collectible drops are on the way.': 'Скоро появятся новые коллекции.',
    '5 collectible Telegram gifts': '5 коллекционных подарков Telegram', 'Demo only': 'Только демо', 'No real GRAM is charged and no NFT is transferred in this preview.': 'GRAM не списываются, а NFT не передаются — это предварительный просмотр.', 'Buy case ·': 'Купить кейс ·', 'POSSIBLE NFTS': 'ВОЗМОЖНЫЕ NFT', 'What you can win': 'Возможные выигрыши', 'Prices in GRAM': 'Цены в GRAM', 'DEMO RESULT': 'РЕЗУЛЬТАТ ДЕМО', 'You got {name}!': 'Ваш выигрыш: {name}!', 'Preview only. No payment was made and this NFT was not added to your profile.': 'Предварительный просмотр. Оплата не списана, NFT не добавлен в профиль.', Continue: 'Продолжить', Open: 'Открыть', 'Opening…': 'Открываем…', 'Demo purchase complete — no GRAM was charged.': 'Демо-покупка завершена — GRAM не списывались.',
    'LUCKY DRAW': 'РОЗЫГРЫШ', 'Try your luck': 'Испытайте удачу', 'One spin. A chance to find something rare.': 'Один спин — шанс найти редкий подарок.', 'Spin cost': 'Цена спина', 'Demo mode: no payment or inventory changes.': 'Демо-режим: без оплаты и изменений инвентаря.', 'Possible rewards': 'Возможные призы', '6 rewards': '6 призов', Spin: 'Крутить', 'Demo result': 'Результат демо', 'You got': 'Ваш выигрыш', 'Demo only. Nothing was charged or added to your inventory.': 'Только демо. GRAM не списывались, подарок не добавлен в инвентарь.', 'GRAM value': 'в GRAM',
    'Refresh profile': 'Обновить профиль', 'Telegram user': 'Пользователь Telegram', 'Telegram account': 'Аккаунт Telegram', 'GRAM wallet': 'Кошелёк GRAM', 'No wallet connected': 'Кошелёк не подключён', Connected: 'Подключён', 'Not connected': 'Не подключён', Owned: 'Мои', Listed: 'Выставлено', Offers: 'Предложения', 'Try again': 'Повторить', 'My gifts': 'Мои подарки', 'No gifts yet': 'Подарков пока нет', 'Gifts you own will appear here.': 'Подарки в вашей собственности появятся здесь.', Sell: 'Продать', 'Listed for sale': 'Выставлено на продажу', 'No active listings': 'Нет активных объявлений', 'Gifts you list for sale will appear here.': 'Подарки, выставленные на продажу, появятся здесь.', 'Reserved for an accepted offer': 'Зарезервировано по принятому предложению', Edit: 'Изменить', Unlist: 'Снять с продажи', 'My offers': 'Мои предложения', 'No active offers': 'Нет активных предложений', 'Offers you make on gifts will appear here.': 'Ваши предложения по подаркам появятся здесь.', 'Cancel offer': 'Отменить предложение', 'Incoming offers': 'Входящие предложения', 'No active incoming offers': 'Нет входящих предложений', 'Offers for your gifts will appear here.': 'Предложения по вашим подаркам появятся здесь.', Accept: 'Принять', 'History': 'История', 'activities': 'действий', 'No activity yet': 'Пока нет активности', 'Completed actions and past offers will appear here.': 'Завершённые действия и прошлые предложения появятся здесь.', 'Edit listing price': 'Изменить цену объявления', 'List gift for sale': 'Выставить подарок на продажу', 'Price in GRAM': 'Цена в GRAM', Cancel: 'Отмена', 'Saving…': 'Сохраняем…', 'Save price': 'Сохранить цену', 'Please wait…': 'Подождите…', Decline: 'Отклонить', 'Release reservation': 'Снять резерв', 'This offer only reserves the gift in ORBIT. Payment and NFT transfer are not automated yet. Release it if the deal will not continue.': 'Это предложение только резервирует подарок в ORBIT. Оплата и передача NFT пока не автоматизированы. Снимите резерв, если сделка не состоится.', 'Gift purchased': 'Подарок куплен', 'Offer accepted · awaiting payment': 'Предложение принято · ожидается оплата', 'Offer cancelled': 'Предложение отменено', 'Offer declined': 'Предложение отклонено', Gift: 'Подарок', 'Your offer': 'Ваше предложение', 'Incoming offer': 'Входящее предложение', 'From @{username}': 'От @{username}',
    'Choose your language': 'Выберите язык', 'Your language is saved on this device.': 'Язык будет сохранён на этом устройстве.', Language: 'Язык', 'Select language': 'Выбрать язык', 'Language updated': 'Язык изменён', Start: 'Начать', 'Your next favorite gift is waiting.': 'Ваш следующий любимый подарок уже ждёт.', 'Browse unique collectibles, discover hidden gems, and trade with ease. Everything you want, all in one place.': 'Изучайте уникальные подарки, находите редкие сокровища и торгуйте с лёгкостью. Всё нужное — в одном месте.', 'DIGITAL COLLECTIBLES': 'ЦИФРОВЫЕ КОЛЛЕКЦИОННЫЕ ПОДАРКИ', 'WELCOME TO ORBIT': 'ДОБРО ПОЖАЛОВАТЬ В ORBIT',
    'Price: low to high': 'Цена: по возрастанию', 'Price: high to low': 'Цена: по убыванию', 'Model rarity: rarest first': 'Редкость модели: сначала редкие', 'Background rarity: rarest first': 'Редкость фона: сначала редкие', 'Symbol rarity: rarest first': 'Редкость символа: сначала редкие',
    'Back to cases': 'Назад к кейсам', CASE: 'КЕЙС', 'Loading profile…': 'Загрузка профиля…', 'items': 'предметов', offers: 'предложений', Pending: 'Ожидает', Accepted: 'Принято', Cancelled: 'Отменено', Rejected: 'Отклонено', Unlisted: 'Снято с продажи', Created: 'Создано', Paid: 'Оплачено', Completed: 'Завершено', 'Gift listed for sale': 'Подарок выставлен на продажу', 'Listing removed': 'Объявление снято', 'Example: 2.5': 'Например: 2.5',
    'Open your profile inside the ORBIT Telegram bot to load your account.': 'Откройте профиль в Telegram-боте ORBIT, чтобы загрузить аккаунт.', 'Could not load profile': 'Не удалось загрузить профиль', 'Could not perform action': 'Не удалось выполнить действие',
  },
};

export function translate(language: OrbitLanguage, key: string) {
  return language === 'en' ? key : translations[language][key] ?? key;
}

export const OrbitLanguageContext = createContext<{
  language: OrbitLanguage;
  setLanguage: (language: OrbitLanguage) => void;
  t: (key: string) => string;
}>({ language: 'en', setLanguage: () => undefined, t: (key) => key });

export function useOrbitLanguage() {
  return useContext(OrbitLanguageContext);
}
