export type TelegramGiftCollection = {
  name: string;
  giftName: string;
  slug: string;
};

// Telegram gift types supplied for the marketplace collection browser.
export const telegramGiftCollections: TelegramGiftCollection[] = [
  { name: 'Artisan Bricks', giftName: 'Artisan Brick', slug: 'artisanbrick' },
  { name: 'Astral Shards', giftName: 'Astral Shard', slug: 'astralshard' },
  { name: 'B-Day Candles', giftName: 'B-Day Candle', slug: 'bdaycandle' },
  { name: 'Berry Boxes', giftName: 'Berry Box', slug: 'berrybox' },
  { name: 'Big Years', giftName: 'Big Year', slug: 'bigyear' },
  { name: 'Bling Binkies', giftName: 'Bling Binky', slug: 'blingbinky' },
  { name: 'Bonded Rings', giftName: 'Bonded Ring', slug: 'bondedring' },
  { name: 'Bow Ties', giftName: 'Bow Tie', slug: 'bowtie' },
  { name: 'Bunny Muffins', giftName: 'Bunny Muffin', slug: 'bunnymuffin' },
  { name: 'Candy Canes', giftName: 'Candy Cane', slug: 'candycane' },
  { name: 'Chill Flames', giftName: 'Chill Flame', slug: 'chillflame' },
  { name: 'Clover Pins', giftName: 'Clover Pin', slug: 'cloverpin' },
  { name: 'Cookie Hearts', giftName: 'Cookie Heart', slug: 'cookieheart' },
  { name: 'Crystal Balls', giftName: 'Crystal Ball', slug: 'crystalball' },
  { name: 'Cupid Charms', giftName: 'Cupid Charm', slug: 'cupidcharm' },
  { name: 'Desk Calendars', giftName: 'Desk Calendar', slug: 'deskcalendar' },
  { name: 'Diamond Rings', giftName: 'Diamond Ring', slug: 'diamondring' },
  { name: "Durov's Caps", giftName: "Durov's Cap", slug: 'durovscap' },
  { name: "Durov's Glasses", giftName: "Durov's Glasses", slug: 'durovsglasses' },
  { name: 'Easter Eggs', giftName: 'Easter Egg', slug: 'easteregg' },
  { name: 'Electric Skulls', giftName: 'Electric Skull', slug: 'electricskull' },
  { name: 'Eternal Candles', giftName: 'Eternal Candle', slug: 'eternalcandle' },
  { name: 'Eternal Roses', giftName: 'Eternal Rose', slug: 'eternalrose' },
  { name: 'Evil Eyes', giftName: 'Evil Eye', slug: 'evileye' },
  { name: 'Faith Amulets', giftName: 'Faith Amulet', slug: 'faithamulet' },
  { name: 'Fine Pens', giftName: 'Fine Pen', slug: 'finepen' },
  { name: 'Flying Brooms', giftName: 'Flying Broom', slug: 'flyingbroom' },
  { name: 'Fresh Socks', giftName: 'Fresh Socks', slug: 'freshsocks' },
  { name: 'Gem Signets', giftName: 'Gem Signet', slug: 'gemsignet' },
  { name: 'Genie Lamps', giftName: 'Genie Lamp', slug: 'genielamp' },
  { name: 'Ginger Cookies', giftName: 'Ginger Cookie', slug: 'gingercookie' },
  { name: 'Hanging Stars', giftName: 'Hanging Star', slug: 'hangingstar' },
  { name: 'Happy Brownies', giftName: 'Happy Brownie', slug: 'happybrownie' },
  { name: 'Heart Lockets', giftName: 'Heart Locket', slug: 'heartlocket' },
  { name: 'Heroic Helmets', giftName: 'Heroic Helmet', slug: 'heroichelmet' },
  { name: 'Hex Pots', giftName: 'Hex Pot', slug: 'hexpot' },
  { name: 'Holiday Drinks', giftName: 'Holiday Drink', slug: 'holidaydrink' },
  { name: 'Homemade Cakes', giftName: 'Homemade Cake', slug: 'homemadecake' },
  { name: 'Hypno Lollipops', giftName: 'Hypno Lollipop', slug: 'hypnolollipop' },
  { name: 'Ice Creams', giftName: 'Ice Cream', slug: 'icecream' },
  { name: 'Input Keys', giftName: 'Input Key', slug: 'inputkey' },
  { name: 'Instant Ramens', giftName: 'Instant Ramen', slug: 'instantramen' },
  { name: 'Ion Gems', giftName: 'Ion Gem', slug: 'iongem' },
  { name: 'Ionic Dryers', giftName: 'Ionic Dryer', slug: 'ionicdryer' },
  { name: 'Jacks-in-the-Box', giftName: 'Jack-in-the-Box', slug: 'jackinthebox' },
  { name: 'Jelly Bunnies', giftName: 'Jelly Bunny', slug: 'jellybunny' },
  { name: 'Jester Hats', giftName: 'Jester Hat', slug: 'jesterhat' },
  { name: 'Jingle Bells', giftName: 'Jingle Bell', slug: 'jinglebell' },
  { name: 'Jolly Chimps', giftName: 'Jolly Chimp', slug: 'jollychimp' },
  { name: 'Joyful Bundles', giftName: 'Joyful Bundle', slug: 'joyfulbundle' },
  { name: "Khabib's Papakhas", giftName: "Khabib's Papakha", slug: 'khabibspapakha' },
  { name: 'Kissed Frogs', giftName: 'Kissed Frog', slug: 'kissedfrog' },
  { name: 'Liberty Figures', giftName: 'Liberty Figure', slug: 'libertyfigure' },
  { name: 'Light Swords', giftName: 'Light Sword', slug: 'lightsword' },
  { name: 'Lol Pops', giftName: 'Lol Pop', slug: 'lolpop' },
  { name: 'Loot Bags', giftName: 'Loot Bag', slug: 'lootbag' },
  { name: 'Love Candles', giftName: 'Love Candle', slug: 'lovecandle' },
  { name: 'Love Potions', giftName: 'Love Potion', slug: 'lovepotion' },
  { name: 'Low Riders', giftName: 'Low Rider', slug: 'lowrider' },
  { name: 'Lunar Snakes', giftName: 'Lunar Snake', slug: 'lunarsnake' },
  { name: 'Lush Bouquets', giftName: 'Lush Bouquet', slug: 'lushbouquet' },
  { name: 'Mad Pumpkins', giftName: 'Mad Pumpkin', slug: 'madpumpkin' },
  { name: 'Magic Potions', giftName: 'Magic Potion', slug: 'magicpotion' },
  { name: 'Mighty Arms', giftName: 'Mighty Arm', slug: 'mightyarm' },
  { name: 'Mini Oscars', giftName: 'Mini Oscar', slug: 'minioscar' },
  { name: 'Money Pots', giftName: 'Money Pot', slug: 'moneypot' },
  { name: 'Mood Packs', giftName: 'Mood Pack', slug: 'moodpack' },
  { name: 'Moon Pendants', giftName: 'Moon Pendant', slug: 'moonpendant' },
  { name: 'Mousse Cakes', giftName: 'Mousse Cake', slug: 'moussecake' },
  { name: 'Nail Bracelets', giftName: 'Nail Bracelet', slug: 'nailbracelet' },
  { name: 'Neko Helmets', giftName: 'Neko Helmet', slug: 'nekohelmet' },
  { name: 'Party Sparklers', giftName: 'Party Sparkler', slug: 'partysparkler' },
  { name: 'Perfume Bottles', giftName: 'Perfume Bottle', slug: 'perfumebottle' },
  { name: 'Pet Snakes', giftName: 'Pet Snake', slug: 'petsnake' },
  { name: 'Plush Pepes', giftName: 'Plush Pepe', slug: 'plushpepe' },
  { name: 'Pool Floats', giftName: 'Pool Float', slug: 'poolfloat' },
  { name: 'Precious Peaches', giftName: 'Precious Peach', slug: 'preciouspeach' },
  { name: 'Pretty Posies', giftName: 'Pretty Posy', slug: 'prettyposy' },
  { name: 'Rare Birds', giftName: 'Rare Bird', slug: 'rarebird' },
  { name: 'Record Players', giftName: 'Record Player', slug: 'recordplayer' },
  { name: 'Restless Jars', giftName: 'Restless Jar', slug: 'restlessjar' },
  { name: 'Sakura Flowers', giftName: 'Sakura Flower', slug: 'sakuraflower' },
  { name: 'Santa Hats', giftName: 'Santa Hat', slug: 'santahat' },
  { name: 'Scared Cats', giftName: 'Scared Cat', slug: 'scaredcat' },
  { name: 'Sharp Tongues', giftName: 'Sharp Tongue', slug: 'sharptongue' },
  { name: 'Signet Rings', giftName: 'Signet Ring', slug: 'signetring' },
  { name: 'Skull Flowers', giftName: 'Skull Flower', slug: 'skullflower' },
  { name: 'Sky Stilettos', giftName: 'Sky Stilettos', slug: 'skystilettos' },
  { name: 'Sleigh Bells', giftName: 'Sleigh Bell', slug: 'sleighbell' },
  { name: 'Snake Boxes', giftName: 'Snake Box', slug: 'snakebox' },
  { name: 'Snoop Cigars', giftName: 'Snoop Cigar', slug: 'snoopcigar' },
  { name: 'Snoop Doggs', giftName: 'Snoop Dogg', slug: 'snoopdogg' },
  { name: 'Snow Globes', giftName: 'Snow Globe', slug: 'snowglobe' },
  { name: 'Snow Mittens', giftName: 'Snow Mittens', slug: 'snowmittens' },
  { name: 'Spiced Wines', giftName: 'Spiced Wine', slug: 'spicedwine' },
  { name: 'Spring Baskets', giftName: 'Spring Basket', slug: 'springbasket' },
  { name: 'Spy Agarics', giftName: 'Spy Agaric', slug: 'spyagaric' },
  { name: 'Star Notepads', giftName: 'Star Notepad', slug: 'starnotepad' },
  { name: 'Stellar Rockets', giftName: 'Stellar Rocket', slug: 'stellarrocket' },
  { name: 'Surge Boards', giftName: 'Surge Board', slug: 'surgeboard' },
  { name: 'Swag Bags', giftName: 'Swag Bag', slug: 'swagbag' },
  { name: 'Swiss Watches', giftName: 'Swiss Watch', slug: 'swisswatch' },
  { name: 'Tama Gadgets', giftName: 'Tama Gadget', slug: 'tamagadget' },
  { name: 'Timeless Books', giftName: 'Timeless Book', slug: 'timelessbook' },
  { name: 'Top Hats', giftName: 'Top Hat', slug: 'tophat' },
  { name: 'Toy Bears', giftName: 'Toy Bear', slug: 'toybear' },
  { name: 'Trapped Hearts', giftName: 'Trapped Heart', slug: 'trappedheart' },
  { name: 'UFC Strikes', giftName: 'UFC Strike', slug: 'ufcstrike' },
  { name: 'Valentine Boxes', giftName: 'Valentine Box', slug: 'valentinebox' },
  { name: 'Vice Creams', giftName: 'Vice Cream', slug: 'vicecream' },
  { name: 'Victory Medals', giftName: 'Victory Medal', slug: 'victorymedal' },
  { name: 'Vintage Cigars', giftName: 'Vintage Cigar', slug: 'vintagecigar' },
  { name: 'Voodoo Dolls', giftName: 'Voodoo Doll', slug: 'voodoodoll' },
  { name: 'Westside Signs', giftName: 'Westside Sign', slug: 'westsidesign' },
  { name: 'Whip Cupcakes', giftName: 'Whip Cupcake', slug: 'whipcupcake' },
  { name: 'Winter Wreaths', giftName: 'Winter Wreath', slug: 'winterwreath' },
  { name: 'Witch Hats', giftName: 'Witch Hat', slug: 'witchhat' },
  { name: 'Xmas Stockings', giftName: 'Xmas Stocking', slug: 'xmasstocking' },
];

export const giftCollectionImage = (slug: string) =>
  `https://fragment.com/file/gifts/${slug}/thumb.webp`;

export function normalizeGiftName(value: string) {
  return value.toLocaleLowerCase().replace(/[^a-z0-9]/g, '');
}
